services:
  liferay:
    image: liferay/dxp:2024.q3.7
    ports:
      - ${LIFERAY_HOST_PORT:-8080}:8080
    volumes:
      - ./liferay/workspace/configs/docker:/mnt/liferay/files:ro
      - ./liferay/workspace/build/docker/client-extensions:/opt/liferay/osgi/client-extensions:ro
      - liferay_data:/opt/liferay/data
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  chatbot-backend:
    build:
      dockerfile: client-extensions/qls-ai-chatbot-etc-backend/Dockerfile
      context: liferay/workspace
    ports:
      - ${CHATBOT_BACKEND_HOST_PORT:-58081}:58081
    depends_on:
      liferay:
        condition: service_healthy
  txtai:
    build:
      dockerfile: Dockerfile
      context: txtai
      args:
        TXTAI_TAG: ${TXTAI_TAG:-latest}
    ports:
      - ${TXTAI_HOST_PORT:-8000}:8000
  elasticsearch:
    build:
      dockerfile: elasticsearch/Dockerfile
      context: .
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
     - ${ELASTICSEARCH_HOST_PORT:-9200}:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - ${KIBANA_HOST_PORT:-5601}:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
  database:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${MYSQL_HOST_PORT:-3306}:3306
    volumes:
      - database_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  liferay_data:
  elasticsearch_data:
  database_data:
  ollama_data:
